[package]
name = "embyr-admin"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "embyr-admin"
path = "src/main.rs"

[dependencies]
embyr-core.workspace = true
tokio.workspace = true
axum.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
chrono.workspace = true
