[package]
name = "embyr-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "embyr-server"
path = "src/main.rs"

[dependencies]
embyr-core.workspace = true
embyr-proto.workspace = true
tokio.workspace = true
tonic.workspace = true
axum.workspace = true
sqlx.workspace = true
rustls.workspace = true
tokio-rustls.workspace = true
argon2.workspace = true
blake3.workspace = true
x25519-dalek.workspace = true
hkdf.workspace = true
aes-gcm.workspace = true
lru.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
config.workspace = true
uuid.workspace = true
chrono.workspace = true
