syntax = "proto3";

package google.protobuf;

option java_package = "com.google.protobuf";
option java_outer_classname = "TimestampProto";

// A Timestamp represents a point in time independent of any time zone or
// calendar, represented as seconds and fractions of seconds at nanosecond
// resolution in UTC Epoch time.
message Timestamp {
  // Represents seconds of UTC time since Unix epoch.
  int64 seconds = 1;

  // Non-negative fractions of a second at nanosecond resolution.
  int32 nanos = 2;
}
